services:
  better-minecraft:
    restart: unless-stopped
    build:
      context: .
    tty: true
    stdin_open: false
    ports:
      - "25565:25565"
    volumes:
      - better_minecraft_world:/server/world

volumes:
  better_minecraft_world:
